[workspace]
resolver = "2"
members = [ "frontend", "backend" ]

[workspace.dependencies]

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
reqwest = { version = "0.12.24", features = ["json"] }
